export const granitDecorRedirects = [
  { source: "/naturalus-akmuo", destination: "/akmuo" },
  { source: "/granitas", destination: "/akmuo?tipas=granitas" },
  { source: "/marmuras", destination: "/akmuo?tipas=marmuras" },
  { source: "/oniksas", destination: "/akmuo?tipas=oniksas" },
  { source: "/travertinas", destination: "/akmuo?tipas=travertinas" },
  { source: "/kvarcitas", destination: "/akmuo?tipas=kvarcitas" },
  { source: "/naturalaus-akmens-gaminiai", destination: "/gaminiai" },
  { source: "/virtuves-stalvirsiai-gamyba", destination: "/gaminiai/virtuves-stalvirsiai" },
  { source: "/vonios-stalvirsiai-gamyba", destination: "/gaminiai/vonios-stalvirsiai" },
  { source: "/židinių-apdaila", destination: "/gaminiai/zidiniu-apdaila" },
  { source: "/laiptai-ir-laiptų-pakopos", destination: "/gaminiai/laiptai-ir-laiptu-pakopos" },
  { source: "/akmeninės-palangės", destination: "/gaminiai/akmens-palanges" },
  { source: "/grindų-danga", destination: "/gaminiai/grindu-danga" },
  { source: "/sienų-apdaila", destination: "/gaminiai/sienu-apdaila" },
  { source: "/vidaus-baldai", destination: "/gaminiai/vidaus-baldai" },
  { source: "/lauko-baldai", destination: "/gaminiai/lauko-baldai" },
  { source: "/fasadų-apdaila", destination: "/gaminiai/fasadu-apdaila" },
  { source: "/kolonos", destination: "/gaminiai/kolonos" },
  { source: "/antkapiai", destination: "/gaminiai/antkapiai-ir-paminklai" },
  { source: "/akmens-gaminiai", destination: "/projektai" },
] as const;
